import type { GitHubAnalysisResult, ResumeClaim } from "@/types";
import { evaluateEvidence } from "./engine";
import type { CandidateVerificationSession } from "./session";

export const SAMPLE_CLAIMS: ResumeClaim[] = [
  {
    id: "claim-react",
    canonicalSkill: "React",
    displayName: "React",
    category: "frontend",
    sourceSection: "SKILLS",
    sourceText: "React.js, Next.js, Redux",
    confidence: 0.95,
    status: "UNVERIFIED",
  },
  {
    id: "claim-nodejs",
    canonicalSkill: "Node.js",
    displayName: "Node.js",
    category: "backend",
    sourceSection: "SKILLS",
    sourceText: "Node.js, Express, REST APIs",
    confidence: 0.95,
    status: "UNVERIFIED",
  },
  {
    id: "claim-docker",
    canonicalSkill: "Docker",
    displayName: "Docker",
    category: "devops",
    sourceSection: "SKILLS",
    sourceText: "Docker containerization and deployment",
    confidence: 0.9,
    status: "UNVERIFIED",
  },
  {
    id: "claim-typescript",
    canonicalSkill: "TypeScript",
    displayName: "TypeScript",
    category: "languages",
    sourceSection: "SKILLS",
    sourceText: "TypeScript, JavaScript ES6+",
    confidence: 0.95,
    status: "UNVERIFIED",
  },
  {
    id: "claim-python",
    canonicalSkill: "Python",
    displayName: "Python",
    category: "languages",
    sourceSection: "SKILLS",
    sourceText: "Python programming and scripts",
    confidence: 0.85,
    status: "UNVERIFIED",
  },
  {
    id: "claim-aws",
    canonicalSkill: "AWS",
    displayName: "AWS",
    category: "cloud",
    sourceSection: "SKILLS",
    sourceText: "AWS S3, EC2 cloud services",
    confidence: 0.8,
    status: "UNVERIFIED",
  },
  {
    id: "claim-kubernetes",
    canonicalSkill: "Kubernetes",
    displayName: "Kubernetes",
    category: "devops",
    sourceSection: "SKILLS",
    sourceText: "Kubernetes cluster orchestration",
    confidence: 0.75,
    status: "UNVERIFIED",
  },
  {
    id: "claim-postgresql",
    canonicalSkill: "PostgreSQL",
    displayName: "PostgreSQL",
    category: "databases",
    sourceSection: "SKILLS",
    sourceText: "PostgreSQL relational databases",
    confidence: 0.85,
    status: "UNVERIFIED",
  },
  {
    id: "claim-git",
    canonicalSkill: "Git",
    displayName: "Git",
    category: "tools",
    sourceSection: "SKILLS",
    sourceText: "Git version control and GitHub",
    confidence: 0.9,
    status: "UNVERIFIED",
  },
  {
    id: "claim-tailwind",
    canonicalSkill: "Tailwind CSS",
    displayName: "Tailwind CSS",
    category: "frontend",
    sourceSection: "SKILLS",
    sourceText: "Tailwind CSS modern styling",
    confidence: 0.9,
    status: "UNVERIFIED",
  },
  {
    id: "claim-express",
    canonicalSkill: "Express",
    displayName: "Express",
    category: "backend",
    sourceSection: "SKILLS",
    sourceText: "Express.js RESTful API architecture",
    confidence: 0.9,
    status: "UNVERIFIED",
  },
];

export const SAMPLE_GITHUB_RESULT: GitHubAnalysisResult = {
  analysisRunId: "run_sample_pratyush_01",
  profile: {
    username: "pratyushwakde24-source",
    name: "Pratyush Wakde",
    avatarUrl: "https://avatars.githubusercontent.com/u/100000000?v=4",
    bio: "Full Stack Developer | Building modern web applications",
    publicRepoCount: 15,
    followers: 12,
    following: 15,
    createdAt: "2022-03-15T00:00:00Z",
    profileUrl: "https://github.com/pratyushwakde24-source",
  },
  summary: {
    repositoriesAnalyzed: 15,
    evidenceItems: 98,
    languagesDetected: ["TypeScript", "JavaScript", "HTML", "CSS"],
    topSkillHints: ["React", "TypeScript", "Node.js", "Express", "Tailwind CSS", "Docker", "Git"],
    lastActiveDate: "2026-09-28T14:22:00Z",
  },
  repositories: [
    {
      id: 101,
      name: "Freshtrust",
      fullName: "pratyushwakde24-source/Freshtrust",
      htmlUrl: "https://github.com/pratyushwakde24-source/Freshtrust",
      description: "Decentralized food supply-chain tracking platform built with React, Node, and Docker.",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      defaultBranch: "main",
      createdAt: "2024-01-10T00:00:00Z",
      updatedAt: "2026-09-20T00:00:00Z",
      pushedAt: "2026-09-20T00:00:00Z",
      stargazersCount: 4,
      forksCount: 1,
      language: "TypeScript",
      topics: ["react", "docker", "supply-chain", "typescript"],
    },
    {
      id: 102,
      name: "SkillForge-Client",
      fullName: "pratyushwakde24-source/SkillForge-Client",
      htmlUrl: "https://github.com/pratyushwakde24-source/SkillForge-Client",
      description: "Frontend client application built with React, Vite, and Tailwind CSS.",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      defaultBranch: "main",
      createdAt: "2024-05-15T00:00:00Z",
      updatedAt: "2026-09-25T00:00:00Z",
      pushedAt: "2026-09-25T00:00:00Z",
      stargazersCount: 2,
      forksCount: 0,
      language: "TypeScript",
      topics: ["react", "tailwind", "vite"],
    },
    {
      id: 103,
      name: "SkillForge-Server",
      fullName: "pratyushwakde24-source/SkillForge-Server",
      htmlUrl: "https://github.com/pratyushwakde24-source/SkillForge-Server",
      description: "Backend REST service using Node.js and Express.",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      defaultBranch: "main",
      createdAt: "2024-05-15T00:00:00Z",
      updatedAt: "2026-09-28T00:00:00Z",
      pushedAt: "2026-09-28T00:00:00Z",
      stargazersCount: 3,
      forksCount: 0,
      language: "JavaScript",
      topics: ["node", "express", "backend"],
    },
    {
      id: 104,
      name: "Portfolio-v2",
      fullName: "pratyushwakde24-source/Portfolio-v2",
      htmlUrl: "https://github.com/pratyushwakde24-source/Portfolio-v2",
      description: "Personal portfolio website with interactive projects.",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      defaultBranch: "main",
      createdAt: "2023-08-01T00:00:00Z",
      updatedAt: "2026-08-10T00:00:00Z",
      pushedAt: "2026-08-10T00:00:00Z",
      stargazersCount: 5,
      forksCount: 0,
      language: "TypeScript",
      topics: ["portfolio", "react"],
    },
    {
      id: 105,
      name: "e-commerce-microservices",
      fullName: "pratyushwakde24-source/e-commerce-microservices",
      htmlUrl: "https://github.com/pratyushwakde24-source/e-commerce-microservices",
      description: "Modular microservices architecture using Express and Node.js.",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      defaultBranch: "main",
      createdAt: "2023-11-20T00:00:00Z",
      updatedAt: "2026-07-15T00:00:00Z",
      pushedAt: "2026-07-15T00:00:00Z",
      stargazersCount: 1,
      forksCount: 0,
      language: "JavaScript",
      topics: ["microservices", "node"],
    },
    {
      id: 106,
      name: "task-tracker",
      fullName: "pratyushwakde24-source/task-tracker",
      htmlUrl: "https://github.com/pratyushwakde24-source/task-tracker",
      description: "Task management web application.",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      defaultBranch: "main",
      createdAt: "2023-04-12T00:00:00Z",
      updatedAt: "2026-06-01T00:00:00Z",
      pushedAt: "2026-06-01T00:00:00Z",
      stargazersCount: 2,
      forksCount: 0,
      language: "TypeScript",
      topics: ["react", "typescript"],
    },
  ],
  evidence: [
    // React evidence
    {
      id: "ev-react-dep-1",
      repositoryName: "Freshtrust",
      type: "dependency",
      skillHints: ["React"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/Freshtrust/blob/main/package.json",
      extractedFact: "react (^18.2.0) detected in package.json dependencies.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-react-dep-2",
      repositoryName: "SkillForge-Client",
      type: "dependency",
      skillHints: ["React"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/SkillForge-Client/blob/main/package.json",
      extractedFact: "react (^18.3.1) detected in package.json dependencies.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-react-dep-3",
      repositoryName: "Portfolio-v2",
      type: "dependency",
      skillHints: ["React"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/Portfolio-v2/blob/main/package.json",
      extractedFact: "react (^18.0.0) detected in package.json dependencies.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-react-dep-4",
      repositoryName: "task-tracker",
      type: "dependency",
      skillHints: ["React"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/task-tracker/blob/main/package.json",
      extractedFact: "react (^18.2.0) detected in package.json dependencies.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-react-framework-1",
      repositoryName: "Freshtrust",
      type: "framework",
      skillHints: ["React"],
      filePath: "src/App.tsx",
      sourceUrl: "https://github.com/pratyushwakde24-source/Freshtrust/blob/main/src/App.tsx",
      extractedFact: "React JSX component imports and React Router hooks detected.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-react-test-1",
      repositoryName: "SkillForge-Client",
      type: "test",
      skillHints: ["React"],
      filePath: "src/components/__tests__/Header.test.tsx",
      sourceUrl: "https://github.com/pratyushwakde24-source/SkillForge-Client/blob/main/src/components/__tests__/Header.test.tsx",
      extractedFact: "@testing-library/react rendering test detected.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-react-commit-1",
      repositoryName: "Freshtrust",
      type: "commit_recency",
      skillHints: ["React", "Git"],
      sourceUrl: "https://github.com/pratyushwakde24-source/Freshtrust/commit/a1b2c3d",
      extractedFact: "Commit on 2026-09-18: 'feat: add reactive dashboard UI components'.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    // Node.js evidence
    {
      id: "ev-node-dep-1",
      repositoryName: "SkillForge-Server",
      type: "dependency",
      skillHints: ["Node.js"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/SkillForge-Server/blob/main/package.json",
      extractedFact: "Node.js engine target >=18.0.0 and @types/node detected.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-node-dep-2",
      repositoryName: "e-commerce-microservices",
      type: "dependency",
      skillHints: ["Node.js"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/e-commerce-microservices/blob/main/package.json",
      extractedFact: "node runtime environment configured in package.json.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-node-dep-3",
      repositoryName: "Freshtrust",
      type: "package_manifest",
      skillHints: ["Node.js"],
      filePath: "server/package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/Freshtrust/blob/main/server/package.json",
      extractedFact: "Node.js server manifest with start script: 'node dist/index.js'.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-node-commit-1",
      repositoryName: "SkillForge-Server",
      type: "commit_recency",
      skillHints: ["Node.js", "Git"],
      sourceUrl: "https://github.com/pratyushwakde24-source/SkillForge-Server/commit/d4e5f6a",
      extractedFact: "Commit on 2026-09-27: 'fix: optimize node async request pipeline'.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    // Express evidence
    {
      id: "ev-express-dep-1",
      repositoryName: "SkillForge-Server",
      type: "dependency",
      skillHints: ["Express"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/SkillForge-Server/blob/main/package.json",
      extractedFact: "express (^4.19.2) detected in package.json dependencies.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-express-framework-1",
      repositoryName: "SkillForge-Server",
      type: "framework",
      skillHints: ["Express"],
      filePath: "src/server.ts",
      sourceUrl: "https://github.com/pratyushwakde24-source/SkillForge-Server/blob/main/src/server.ts",
      extractedFact: "Express middleware setup and Router declaration detected.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-express-dep-2",
      repositoryName: "e-commerce-microservices",
      type: "dependency",
      skillHints: ["Express"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/e-commerce-microservices/blob/main/package.json",
      extractedFact: "express dependency detected in microservices root.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    // TypeScript evidence
    {
      id: "ev-ts-lang-1",
      repositoryName: "Freshtrust",
      type: "repository_language",
      skillHints: ["TypeScript"],
      sourceUrl: "https://github.com/pratyushwakde24-source/Freshtrust",
      extractedFact: "TypeScript detected as primary repository language (64% of codebase).",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-ts-dep-1",
      repositoryName: "Freshtrust",
      type: "dependency",
      skillHints: ["TypeScript"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/Freshtrust/blob/main/package.json",
      extractedFact: "typescript (^5.2.0) detected in devDependencies.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-ts-lang-2",
      repositoryName: "SkillForge-Client",
      type: "repository_language",
      skillHints: ["TypeScript"],
      sourceUrl: "https://github.com/pratyushwakde24-source/SkillForge-Client",
      extractedFact: "TypeScript detected as primary repository language (78% of codebase).",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    // Tailwind CSS evidence
    {
      id: "ev-tailwind-dep-1",
      repositoryName: "SkillForge-Client",
      type: "dependency",
      skillHints: ["Tailwind CSS"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/SkillForge-Client/blob/main/package.json",
      extractedFact: "tailwindcss (^3.4.1) detected in devDependencies.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-tailwind-cfg-1",
      repositoryName: "SkillForge-Client",
      type: "package_manifest",
      skillHints: ["Tailwind CSS"],
      filePath: "tailwind.config.js",
      sourceUrl: "https://github.com/pratyushwakde24-source/SkillForge-Client/blob/main/tailwind.config.js",
      extractedFact: "Tailwind CSS configuration file detected with theme extensions.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-tailwind-dep-2",
      repositoryName: "Portfolio-v2",
      type: "dependency",
      skillHints: ["Tailwind CSS"],
      filePath: "package.json",
      sourceUrl: "https://github.com/pratyushwakde24-source/Portfolio-v2/blob/main/package.json",
      extractedFact: "tailwindcss detected in package.json.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    // Git evidence
    {
      id: "ev-git-commit-1",
      repositoryName: "Freshtrust",
      type: "commit_recency",
      skillHints: ["Git"],
      sourceUrl: "https://github.com/pratyushwakde24-source/Freshtrust/commits",
      extractedFact: "Active Git commit history: 34 commits recorded.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-git-commit-2",
      repositoryName: "SkillForge-Server",
      type: "commit_recency",
      skillHints: ["Git"],
      sourceUrl: "https://github.com/pratyushwakde24-source/SkillForge-Server/commits",
      extractedFact: "Active Git commit history: 28 commits recorded.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    // Docker evidence (PARTIAL)
    {
      id: "ev-docker-1",
      repositoryName: "Freshtrust",
      type: "dockerfile",
      skillHints: ["Docker"],
      filePath: "Dockerfile",
      sourceUrl: "https://github.com/pratyushwakde24-source/Freshtrust/blob/main/Dockerfile",
      extractedFact: "Dockerfile found with multi-stage build: node:18-alpine base image.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
    {
      id: "ev-docker-2",
      repositoryName: "Freshtrust",
      type: "docker_compose",
      skillHints: ["Docker"],
      filePath: "docker-compose.yml",
      sourceUrl: "https://github.com/pratyushwakde24-source/Freshtrust/blob/main/docker-compose.yml",
      extractedFact: "docker-compose.yml configuring web and database service containers.",
      collectedAt: "2026-09-28T00:00:00Z",
      analyzerVersion: "1.0.0",
    },
  ],
};

/**
 * Creates an authentic sample candidate verification session using real Phase 4 deterministic evaluation.
 */
export function createSampleVerificationSession(): CandidateVerificationSession {
  const evaluation = evaluateEvidence(
    SAMPLE_CLAIMS,
    SAMPLE_GITHUB_RESULT.evidence,
    SAMPLE_GITHUB_RESULT.repositories
  );

  return {
    candidate: {
      name: "Pratyush Wakde",
      email: "pratyush@example.com",
    },
    githubUsername: "pratyushwakde24-source",
    analyzedAt: "2026-10-02T13:45:00.000Z",
    metadata: {
      filename: "pratyush-wakde-resume.pdf",
      pageCount: 1,
    },
    claims: SAMPLE_CLAIMS,
    githubResult: SAMPLE_GITHUB_RESULT,
    evaluation,
  };
}
